using Avalonia;
using Avalonia.Rendering.Composition.Animations;
using Avalonia.Rendering.Composition.Expressions;
using Avalonia.Rendering.Composition.Transport;

namespace SmoothScroll.Avalonia.Interaction;

/// <summary>
/// This file is generated by CompositionGenerator in Avalonia. 
/// Do not edit this file directly. Instead, edit composition-schema.xml in Avalonia and copy the generated code to this file.
/// </summary>
public partial class InteractionTracker
{
    InteractionTrackerChangedFields _changedFieldsOfInteractionTracker;
    double _minScale;
    public double MinScale
    {
        get
        {
            return _minScale;
        }

        set
        {
            var changed = false;
            if (_minScale != value)
            {
                ValidateMinScaleChange(_minScale, value);
                OnMinScaleChanging();
                changed = true;
                {
                    // Update the backing value
                    _minScale = value;
                    // Register object for serialization in the next batch
                    _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MinScale;
                    RegisterForSerialization();
                    // Reset previous animation if any
                    PendingAnimations.Remove(ServerInteractionTracker.s_IdOfMinScaleProperty);
                    _changedFieldsOfInteractionTracker &= ~InteractionTrackerChangedFields.MinScaleAnimated;
                    // Check for implicit animations
                    if (ImplicitAnimations != null && ImplicitAnimations.TryGetValue("MinScale", out var animation) == true)
                    {
                        // Animation affects only current property
                        if (animation is CompositionAnimation a)
                        {
                            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MinScaleAnimated;
                            PendingAnimations[ServerInteractionTracker.s_IdOfMinScaleProperty] = a.CreateInstance(this.Server, value);
                        }

                        // Animation is triggered by the current field, but does not necessary affects it
                        StartAnimationGroup(animation, "MinScale", value);
                    }
                }
            }

            _minScale = value;
            if (changed)
                OnMinScaleChanged();
        }
    }

    partial void ValidateMinScaleChange(double oldValue, double newValue);
    partial void OnMinScaleChanged();
    partial void OnMinScaleChanging();
    double _maxScale;
    public double MaxScale
    {
        get
        {
            return _maxScale;
        }

        set
        {
            var changed = false;
            if (_maxScale != value)
            {
                ValidateMaxScaleChange(_maxScale, value);
                OnMaxScaleChanging();
                changed = true;
                {
                    // Update the backing value
                    _maxScale = value;
                    // Register object for serialization in the next batch
                    _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MaxScale;
                    RegisterForSerialization();
                    // Reset previous animation if any
                    PendingAnimations.Remove(ServerInteractionTracker.s_IdOfMaxScaleProperty);
                    _changedFieldsOfInteractionTracker &= ~InteractionTrackerChangedFields.MaxScaleAnimated;
                    // Check for implicit animations
                    if (ImplicitAnimations != null && ImplicitAnimations.TryGetValue("MaxScale", out var animation) == true)
                    {
                        // Animation affects only current property
                        if (animation is CompositionAnimation a)
                        {
                            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MaxScaleAnimated;
                            PendingAnimations[ServerInteractionTracker.s_IdOfMaxScaleProperty] = a.CreateInstance(this.Server, value);
                        }

                        // Animation is triggered by the current field, but does not necessary affects it
                        StartAnimationGroup(animation, "MaxScale", value);
                    }
                }
            }

            _maxScale = value;
            if (changed)
                OnMaxScaleChanged();
        }
    }

    partial void ValidateMaxScaleChange(double oldValue, double newValue);
    partial void OnMaxScaleChanged();
    partial void OnMaxScaleChanging();
    Vector3D _minPosition;
    public Vector3D MinPosition
    {
        get
        {
            return _minPosition;
        }

        set
        {
            var changed = false;
            if (_minPosition != value)
            {
                ValidateMinPositionChange(_minPosition, value);
                OnMinPositionChanging();
                changed = true;
                {
                    // Update the backing value
                    _minPosition = value;
                    // Register object for serialization in the next batch
                    _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MinPosition;
                    RegisterForSerialization();
                    // Reset previous animation if any
                    PendingAnimations.Remove(ServerInteractionTracker.s_IdOfMinPositionProperty);
                    _changedFieldsOfInteractionTracker &= ~InteractionTrackerChangedFields.MinPositionAnimated;
                    // Check for implicit animations
                    if (ImplicitAnimations != null && ImplicitAnimations.TryGetValue("MinPosition", out var animation) == true)
                    {
                        // Animation affects only current property
                        if (animation is CompositionAnimation a)
                        {
                            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MinPositionAnimated;
                            PendingAnimations[ServerInteractionTracker.s_IdOfMinPositionProperty] = a.CreateInstance(this.Server, value);
                        }

                        // Animation is triggered by the current field, but does not necessary affects it
                        StartAnimationGroup(animation, "MinPosition", value);
                    }
                }
            }

            _minPosition = value;
            if (changed)
                OnMinPositionChanged();
        }
    }

    partial void ValidateMinPositionChange(Vector3D oldValue, Vector3D newValue);
    partial void OnMinPositionChanged();
    partial void OnMinPositionChanging();
    Vector3D _maxPosition;
    public Vector3D MaxPosition
    {
        get
        {
            return _maxPosition;
        }

        set
        {
            var changed = false;
            if (_maxPosition != value)
            {
                ValidateMaxPositionChange(_maxPosition, value);
                OnMaxPositionChanging();
                changed = true;
                {
                    // Update the backing value
                    _maxPosition = value;
                    // Register object for serialization in the next batch
                    _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MaxPosition;
                    RegisterForSerialization();
                    // Reset previous animation if any
                    PendingAnimations.Remove(ServerInteractionTracker.s_IdOfMaxPositionProperty);
                    _changedFieldsOfInteractionTracker &= ~InteractionTrackerChangedFields.MaxPositionAnimated;
                    // Check for implicit animations
                    if (ImplicitAnimations != null && ImplicitAnimations.TryGetValue("MaxPosition", out var animation) == true)
                    {
                        // Animation affects only current property
                        if (animation is CompositionAnimation a)
                        {
                            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MaxPositionAnimated;
                            PendingAnimations[ServerInteractionTracker.s_IdOfMaxPositionProperty] = a.CreateInstance(this.Server, value);
                        }

                        // Animation is triggered by the current field, but does not necessary affects it
                        StartAnimationGroup(animation, "MaxPosition", value);
                    }
                }
            }

            _maxPosition = value;
            if (changed)
                OnMaxPositionChanged();
        }
    }

    partial void ValidateMaxPositionChange(Vector3D oldValue, Vector3D newValue);
    partial void OnMaxPositionChanged();
    partial void OnMaxPositionChanging();
    Vector3D _positionInertiaDecayRate;
    public Vector3D PositionInertiaDecayRate
    {
        get
        {
            return _positionInertiaDecayRate;
        }

        set
        {
            var changed = false;
            if (_positionInertiaDecayRate != value)
            {
                ValidatePositionInertiaDecayRateChange(_positionInertiaDecayRate, value);
                OnPositionInertiaDecayRateChanging();
                changed = true;
                {
                    // Update the backing value
                    _positionInertiaDecayRate = value;
                    // Register object for serialization in the next batch
                    _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.PositionInertiaDecayRate;
                    RegisterForSerialization();
                    // Reset previous animation if any
                    PendingAnimations.Remove(ServerInteractionTracker.s_IdOfPositionInertiaDecayRateProperty);
                    _changedFieldsOfInteractionTracker &= ~InteractionTrackerChangedFields.PositionInertiaDecayRateAnimated;
                    // Check for implicit animations
                    if (ImplicitAnimations != null && ImplicitAnimations.TryGetValue("PositionInertiaDecayRate", out var animation) == true)
                    {
                        // Animation affects only current property
                        if (animation is CompositionAnimation a)
                        {
                            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.PositionInertiaDecayRateAnimated;
                            PendingAnimations[ServerInteractionTracker.s_IdOfPositionInertiaDecayRateProperty] = a.CreateInstance(this.Server, value);
                        }

                        // Animation is triggered by the current field, but does not necessary affects it
                        StartAnimationGroup(animation, "PositionInertiaDecayRate", value);
                    }
                }
            }

            _positionInertiaDecayRate = value;
            if (changed)
                OnPositionInertiaDecayRateChanged();
        }
    }

    partial void ValidatePositionInertiaDecayRateChange(Vector3D oldValue, Vector3D newValue);
    partial void OnPositionInertiaDecayRateChanged();
    partial void OnPositionInertiaDecayRateChanging();
    double _scaleInertiaDecayRate;
    public double ScaleInertiaDecayRate
    {
        get
        {
            return _scaleInertiaDecayRate;
        }

        set
        {
            var changed = false;
            if (_scaleInertiaDecayRate != value)
            {
                ValidateScaleInertiaDecayRateChange(_scaleInertiaDecayRate, value);
                OnScaleInertiaDecayRateChanging();
                changed = true;
                {
                    // Update the backing value
                    _scaleInertiaDecayRate = value;
                    // Register object for serialization in the next batch
                    _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.ScaleInertiaDecayRate;
                    RegisterForSerialization();
                    // Reset previous animation if any
                    PendingAnimations.Remove(ServerInteractionTracker.s_IdOfScaleInertiaDecayRateProperty);
                    _changedFieldsOfInteractionTracker &= ~InteractionTrackerChangedFields.ScaleInertiaDecayRateAnimated;
                    // Check for implicit animations
                    if (ImplicitAnimations != null && ImplicitAnimations.TryGetValue("ScaleInertiaDecayRate", out var animation) == true)
                    {
                        // Animation affects only current property
                        if (animation is CompositionAnimation a)
                        {
                            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.ScaleInertiaDecayRateAnimated;
                            PendingAnimations[ServerInteractionTracker.s_IdOfScaleInertiaDecayRateProperty] = a.CreateInstance(this.Server, value);
                        }

                        // Animation is triggered by the current field, but does not necessary affects it
                        StartAnimationGroup(animation, "ScaleInertiaDecayRate", value);
                    }
                }
            }

            _scaleInertiaDecayRate = value;
            if (changed)
                OnScaleInertiaDecayRateChanged();
        }
    }

    partial void ValidateScaleInertiaDecayRateChange(double oldValue, double newValue);
    partial void OnScaleInertiaDecayRateChanged();
    partial void OnScaleInertiaDecayRateChanging();
    double _scale;
    public double Scale
    {
        get
        {
            return _scale;
        }

        set
        {
            var changed = false;
            if (_scale != value)
            {
                ValidateScaleChange(_scale, value);
                OnScaleChanging();
                changed = true;
                {
                    // Update the backing value
                    _scale = value;
                    // Register object for serialization in the next batch
                    _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.Scale;
                    RegisterForSerialization();
                    // Reset previous animation if any
                    PendingAnimations.Remove(ServerInteractionTracker.s_IdOfScaleProperty);
                    _changedFieldsOfInteractionTracker &= ~InteractionTrackerChangedFields.ScaleAnimated;
                    // Check for implicit animations
                    if (ImplicitAnimations != null && ImplicitAnimations.TryGetValue("Scale", out var animation) == true)
                    {
                        // Animation affects only current property
                        if (animation is CompositionAnimation a)
                        {
                            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.ScaleAnimated;
                            PendingAnimations[ServerInteractionTracker.s_IdOfScaleProperty] = a.CreateInstance(this.Server, value);
                        }

                        // Animation is triggered by the current field, but does not necessary affects it
                        StartAnimationGroup(animation, "Scale", value);
                    }
                }
            }

            _scale = value;
            if (changed)
                OnScaleChanged();
        }
    }

    partial void ValidateScaleChange(double oldValue, double newValue);
    partial void OnScaleChanged();
    partial void OnScaleChanging();
    Vector3D _position;
    public Vector3D Position
    {
        get
        {
            return _position;
        }

        set
        {
            var changed = false;
            if (_position != value)
            {
                ValidatePositionChange(_position, value);
                OnPositionChanging();
                changed = true;
                {
                    // Update the backing value
                    _position = value;
                    // Register object for serialization in the next batch
                    _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.Position;
                    RegisterForSerialization();
                    // Reset previous animation if any
                    PendingAnimations.Remove(ServerInteractionTracker.s_IdOfPositionProperty);
                    _changedFieldsOfInteractionTracker &= ~InteractionTrackerChangedFields.PositionAnimated;
                    // Check for implicit animations
                    if (ImplicitAnimations != null && ImplicitAnimations.TryGetValue("Position", out var animation) == true)
                    {
                        // Animation affects only current property
                        if (animation is CompositionAnimation a)
                        {
                            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.PositionAnimated;
                            PendingAnimations[ServerInteractionTracker.s_IdOfPositionProperty] = a.CreateInstance(this.Server, value);
                        }

                        // Animation is triggered by the current field, but does not necessary affects it
                        StartAnimationGroup(animation, "Position", value);
                    }
                }
            }

            _position = value;
            if (changed)
                OnPositionChanged();
        }
    }

    partial void ValidatePositionChange(Vector3D oldValue, Vector3D newValue);
    partial void OnPositionChanged();
    partial void OnPositionChanging();
    void InitializeDefaults()
    {
        InitializeDefaultsExtra();
        PositionInertiaDecayRate = new Vector3D(0.95, 0.95, 0.95);
    }

    partial void InitializeDefaultsExtra();
    partial void SerializeRequests(BatchStreamWriter writer);
    public override void SerializeChangesCore(BatchStreamWriter writer)
    {
        base.SerializeChangesCore(writer);
        writer.Write(_changedFieldsOfInteractionTracker);
        if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.MinScaleAnimated) == InteractionTrackerChangedFields.MinScaleAnimated)
            writer.WriteObject(PendingAnimations.GetAndRemove(ServerInteractionTracker.s_IdOfMinScaleProperty));
        else if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.MinScale) == InteractionTrackerChangedFields.MinScale)
            writer.Write(_minScale);
        if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.MaxScaleAnimated) == InteractionTrackerChangedFields.MaxScaleAnimated)
            writer.WriteObject(PendingAnimations.GetAndRemove(ServerInteractionTracker.s_IdOfMaxScaleProperty));
        else if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.MaxScale) == InteractionTrackerChangedFields.MaxScale)
            writer.Write(_maxScale);
        if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.MinPositionAnimated) == InteractionTrackerChangedFields.MinPositionAnimated)
            writer.WriteObject(PendingAnimations.GetAndRemove(ServerInteractionTracker.s_IdOfMinPositionProperty));
        else if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.MinPosition) == InteractionTrackerChangedFields.MinPosition)
            writer.Write(_minPosition);
        if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.MaxPositionAnimated) == InteractionTrackerChangedFields.MaxPositionAnimated)
            writer.WriteObject(PendingAnimations.GetAndRemove(ServerInteractionTracker.s_IdOfMaxPositionProperty));
        else if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.MaxPosition) == InteractionTrackerChangedFields.MaxPosition)
            writer.Write(_maxPosition);
        if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.PositionInertiaDecayRateAnimated) == InteractionTrackerChangedFields.PositionInertiaDecayRateAnimated)
            writer.WriteObject(PendingAnimations.GetAndRemove(ServerInteractionTracker.s_IdOfPositionInertiaDecayRateProperty));
        else if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.PositionInertiaDecayRate) == InteractionTrackerChangedFields.PositionInertiaDecayRate)
            writer.Write(_positionInertiaDecayRate);
        if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.ScaleInertiaDecayRateAnimated) == InteractionTrackerChangedFields.ScaleInertiaDecayRateAnimated)
            writer.WriteObject(PendingAnimations.GetAndRemove(ServerInteractionTracker.s_IdOfScaleInertiaDecayRateProperty));
        else if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.ScaleInertiaDecayRate) == InteractionTrackerChangedFields.ScaleInertiaDecayRate)
            writer.Write(_scaleInertiaDecayRate);
        if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.ScaleAnimated) == InteractionTrackerChangedFields.ScaleAnimated)
            writer.WriteObject(PendingAnimations.GetAndRemove(ServerInteractionTracker.s_IdOfScaleProperty));
        else if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.Scale) == InteractionTrackerChangedFields.Scale)
            writer.Write(_scale);
        if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.PositionAnimated) == InteractionTrackerChangedFields.PositionAnimated)
            writer.WriteObject(PendingAnimations.GetAndRemove(ServerInteractionTracker.s_IdOfPositionProperty));
        else if ((_changedFieldsOfInteractionTracker & InteractionTrackerChangedFields.Position) == InteractionTrackerChangedFields.Position)
            writer.Write(_position);
        {
            _changedFieldsOfInteractionTracker = default;
        }
        SerializeRequests(writer);
    }

    public override void StartAnimation(string propertyName, CompositionAnimation animation, ExpressionVariant? finalValue)
    {
        if (propertyName == "MinScale")
        {
            var current = _minScale;
            var server = animation.CreateInstance(this.Server, finalValue);
            PendingAnimations[ServerInteractionTracker.s_IdOfMinScaleProperty] = server;
            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MinScaleAnimated;
            RegisterForSerialization();
            return;
        }

        if (propertyName == "MaxScale")
        {
            var current = _maxScale;
            var server = animation.CreateInstance(this.Server, finalValue);
            PendingAnimations[ServerInteractionTracker.s_IdOfMaxScaleProperty] = server;
            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MaxScaleAnimated;
            RegisterForSerialization();
            return;
        }

        if (propertyName == "MinPosition")
        {
            var current = _minPosition;
            var server = animation.CreateInstance(this.Server, finalValue);
            PendingAnimations[ServerInteractionTracker.s_IdOfMinPositionProperty] = server;
            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MinPositionAnimated;
            RegisterForSerialization();
            return;
        }

        if (propertyName == "MaxPosition")
        {
            var current = _maxPosition;
            var server = animation.CreateInstance(this.Server, finalValue);
            PendingAnimations[ServerInteractionTracker.s_IdOfMaxPositionProperty] = server;
            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.MaxPositionAnimated;
            RegisterForSerialization();
            return;
        }

        if (propertyName == "PositionInertiaDecayRate")
        {
            var current = _positionInertiaDecayRate;
            var server = animation.CreateInstance(this.Server, finalValue);
            PendingAnimations[ServerInteractionTracker.s_IdOfPositionInertiaDecayRateProperty] = server;
            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.PositionInertiaDecayRateAnimated;
            RegisterForSerialization();
            return;
        }

        if (propertyName == "ScaleInertiaDecayRate")
        {
            var current = _scaleInertiaDecayRate;
            var server = animation.CreateInstance(this.Server, finalValue);
            PendingAnimations[ServerInteractionTracker.s_IdOfScaleInertiaDecayRateProperty] = server;
            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.ScaleInertiaDecayRateAnimated;
            RegisterForSerialization();
            return;
        }

        if (propertyName == "Scale")
        {
            var current = _scale;
            var server = animation.CreateInstance(this.Server, finalValue);
            PendingAnimations[ServerInteractionTracker.s_IdOfScaleProperty] = server;
            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.ScaleAnimated;
            RegisterForSerialization();
            return;
        }

        if (propertyName == "Position")
        {
            var current = _position;
            var server = animation.CreateInstance(this.Server, finalValue);
            PendingAnimations[ServerInteractionTracker.s_IdOfPositionProperty] = server;
            _changedFieldsOfInteractionTracker |= InteractionTrackerChangedFields.PositionAnimated;
            RegisterForSerialization();
            return;
        }

        base.StartAnimation(propertyName, animation, finalValue);
    }
}
