using Avalonia;
using Avalonia.Rendering.Composition.Animations;
using Avalonia.Rendering.Composition.Server;
using Avalonia.Rendering.Composition.Transport;

namespace SmoothScroll.Avalonia.Interaction;

/// <summary>
/// This file is generated by CompositionGenerator in Avalonia. 
/// Do not edit this file directly. Instead, edit composition-schema.xml in Avalonia and copy the generated code to this file.
/// </summary>
#nullable enable
partial class ServerInteractionTracker : ServerObject
{
    internal ServerInteractionTracker(ServerCompositor compositor) : base(compositor)
    {
        Initialize();
    }

    partial void Initialize();
    partial void DeserializeChangesExtra(BatchStreamReader c);
    double _minScale;
    public double MinScale { get => _minScale; set => SetAnimatedValue(s_IdOfMinScaleProperty, out _minScale, value); }

    internal readonly static CompositionProperty<double> s_IdOfMinScaleProperty = CompositionProperty.Register<ServerInteractionTracker, double>("MinScale", obj => ((ServerInteractionTracker)obj)._minScale, (obj, v) => ((ServerInteractionTracker)obj)._minScale = v, obj => ((ServerInteractionTracker)obj)._minScale);
    double _maxScale;
    public double MaxScale { get => _maxScale; set => SetAnimatedValue(s_IdOfMaxScaleProperty, out _maxScale, value); }

    internal readonly static CompositionProperty<double> s_IdOfMaxScaleProperty = CompositionProperty.Register<ServerInteractionTracker, double>("MaxScale", obj => ((ServerInteractionTracker)obj)._maxScale, (obj, v) => ((ServerInteractionTracker)obj)._maxScale = v, obj => ((ServerInteractionTracker)obj)._maxScale);
    Vector3D _minPosition;
    public Vector3D MinPosition { get => _minPosition; set => SetAnimatedValue(s_IdOfMinPositionProperty, out _minPosition, value); }

    internal readonly static CompositionProperty<Vector3D> s_IdOfMinPositionProperty = CompositionProperty.Register<ServerInteractionTracker, Vector3D>("MinPosition", obj => ((ServerInteractionTracker)obj)._minPosition, (obj, v) => ((ServerInteractionTracker)obj)._minPosition = v, obj => ((ServerInteractionTracker)obj)._minPosition);
    Vector3D _maxPosition;
    public Vector3D MaxPosition { get => _maxPosition; set => SetAnimatedValue(s_IdOfMaxPositionProperty, out _maxPosition, value); }

    internal readonly static CompositionProperty<Vector3D> s_IdOfMaxPositionProperty = CompositionProperty.Register<ServerInteractionTracker, Vector3D>("MaxPosition", obj => ((ServerInteractionTracker)obj)._maxPosition, (obj, v) => ((ServerInteractionTracker)obj)._maxPosition = v, obj => ((ServerInteractionTracker)obj)._maxPosition);
    Vector3D _positionInertiaDecayRate;
    public Vector3D PositionInertiaDecayRate { get => _positionInertiaDecayRate; set => SetAnimatedValue(s_IdOfPositionInertiaDecayRateProperty, out _positionInertiaDecayRate, value); }

    internal readonly static CompositionProperty<Vector3D> s_IdOfPositionInertiaDecayRateProperty = CompositionProperty.Register<ServerInteractionTracker, Vector3D>("PositionInertiaDecayRate", obj => ((ServerInteractionTracker)obj)._positionInertiaDecayRate, (obj, v) => ((ServerInteractionTracker)obj)._positionInertiaDecayRate = v, obj => ((ServerInteractionTracker)obj)._positionInertiaDecayRate);
    double _scaleInertiaDecayRate;
    public double ScaleInertiaDecayRate { get => _scaleInertiaDecayRate; set => SetAnimatedValue(s_IdOfScaleInertiaDecayRateProperty, out _scaleInertiaDecayRate, value); }

    internal readonly static CompositionProperty<double> s_IdOfScaleInertiaDecayRateProperty = CompositionProperty.Register<ServerInteractionTracker, double>("ScaleInertiaDecayRate", obj => ((ServerInteractionTracker)obj)._scaleInertiaDecayRate, (obj, v) => ((ServerInteractionTracker)obj)._scaleInertiaDecayRate = v, obj => ((ServerInteractionTracker)obj)._scaleInertiaDecayRate);
    double _scale;
    public double Scale { get => _scale; set => SetAnimatedValue(s_IdOfScaleProperty, out _scale, value); }

    internal readonly static CompositionProperty<double> s_IdOfScaleProperty = CompositionProperty.Register<ServerInteractionTracker, double>("Scale", obj => ((ServerInteractionTracker)obj)._scale, (obj, v) => ((ServerInteractionTracker)obj)._scale = v, obj => ((ServerInteractionTracker)obj)._scale);
    Vector3D _position;
    public Vector3D Position { get => _position; set => SetAnimatedValue(s_IdOfPositionProperty, out _position, value); }

    internal readonly static CompositionProperty<Vector3D> s_IdOfPositionProperty = CompositionProperty.Register<ServerInteractionTracker, Vector3D>("Position", obj => ((ServerInteractionTracker)obj)._position, (obj, v) => ((ServerInteractionTracker)obj)._position = v, obj => ((ServerInteractionTracker)obj)._position);
    protected override void DeserializeChangesCore(BatchStreamReader reader, TimeSpan committedAt)
    {
        base.DeserializeChangesCore(reader, committedAt);
        DeserializeChangesExtra(reader);
        var changed = reader.Read<InteractionTrackerChangedFields>();
        if ((changed & InteractionTrackerChangedFields.MinScaleAnimated) == InteractionTrackerChangedFields.MinScaleAnimated)
            SetAnimatedValue(s_IdOfMinScaleProperty, ref _minScale, committedAt, reader.ReadObject<IAnimationInstance>());
        else if ((changed & InteractionTrackerChangedFields.MinScale) == InteractionTrackerChangedFields.MinScale)
            MinScale = reader.Read<double>();
        if ((changed & InteractionTrackerChangedFields.MaxScaleAnimated) == InteractionTrackerChangedFields.MaxScaleAnimated)
            SetAnimatedValue(s_IdOfMaxScaleProperty, ref _maxScale, committedAt, reader.ReadObject<IAnimationInstance>());
        else if ((changed & InteractionTrackerChangedFields.MaxScale) == InteractionTrackerChangedFields.MaxScale)
            MaxScale = reader.Read<double>();
        if ((changed & InteractionTrackerChangedFields.MinPositionAnimated) == InteractionTrackerChangedFields.MinPositionAnimated)
            SetAnimatedValue(s_IdOfMinPositionProperty, ref _minPosition, committedAt, reader.ReadObject<IAnimationInstance>());
        else if ((changed & InteractionTrackerChangedFields.MinPosition) == InteractionTrackerChangedFields.MinPosition)
            MinPosition = reader.Read<Vector3D>();
        if ((changed & InteractionTrackerChangedFields.MaxPositionAnimated) == InteractionTrackerChangedFields.MaxPositionAnimated)
            SetAnimatedValue(s_IdOfMaxPositionProperty, ref _maxPosition, committedAt, reader.ReadObject<IAnimationInstance>());
        else if ((changed & InteractionTrackerChangedFields.MaxPosition) == InteractionTrackerChangedFields.MaxPosition)
            MaxPosition = reader.Read<Vector3D>();
        if ((changed & InteractionTrackerChangedFields.PositionInertiaDecayRateAnimated) == InteractionTrackerChangedFields.PositionInertiaDecayRateAnimated)
            SetAnimatedValue(s_IdOfPositionInertiaDecayRateProperty, ref _positionInertiaDecayRate, committedAt, reader.ReadObject<IAnimationInstance>());
        else if ((changed & InteractionTrackerChangedFields.PositionInertiaDecayRate) == InteractionTrackerChangedFields.PositionInertiaDecayRate)
            PositionInertiaDecayRate = reader.Read<Vector3D>();
        if ((changed & InteractionTrackerChangedFields.ScaleInertiaDecayRateAnimated) == InteractionTrackerChangedFields.ScaleInertiaDecayRateAnimated)
            SetAnimatedValue(s_IdOfScaleInertiaDecayRateProperty, ref _scaleInertiaDecayRate, committedAt, reader.ReadObject<IAnimationInstance>());
        else if ((changed & InteractionTrackerChangedFields.ScaleInertiaDecayRate) == InteractionTrackerChangedFields.ScaleInertiaDecayRate)
            ScaleInertiaDecayRate = reader.Read<double>();
        if ((changed & InteractionTrackerChangedFields.ScaleAnimated) == InteractionTrackerChangedFields.ScaleAnimated)
            SetAnimatedValue(s_IdOfScaleProperty, ref _scale, committedAt, reader.ReadObject<IAnimationInstance>());
        else if ((changed & InteractionTrackerChangedFields.Scale) == InteractionTrackerChangedFields.Scale)
            Scale = reader.Read<double>();
        if ((changed & InteractionTrackerChangedFields.PositionAnimated) == InteractionTrackerChangedFields.PositionAnimated)
            SetAnimatedValue(s_IdOfPositionProperty, ref _position, committedAt, reader.ReadObject<IAnimationInstance>());
        else if ((changed & InteractionTrackerChangedFields.Position) == InteractionTrackerChangedFields.Position)
            Position = reader.Read<Vector3D>();
        OnFieldsDeserialized(changed);
        DeserializeRequests(reader);
    }
    partial void DeserializeRequests(BatchStreamReader reader);
    partial void OnFieldsDeserialized(InteractionTrackerChangedFields changed);
    public override CompositionProperty? GetCompositionProperty(string name)
    {
        if (name == "MinScale")
            return s_IdOfMinScaleProperty;
        if (name == "MaxScale")
            return s_IdOfMaxScaleProperty;
        if (name == "MinPosition")
            return s_IdOfMinPositionProperty;
        if (name == "MaxPosition")
            return s_IdOfMaxPositionProperty;
        if (name == "PositionInertiaDecayRate")
            return s_IdOfPositionInertiaDecayRateProperty;
        if (name == "ScaleInertiaDecayRate")
            return s_IdOfScaleInertiaDecayRateProperty;
        if (name == "Scale")
            return s_IdOfScaleProperty;
        if (name == "Position")
            return s_IdOfPositionProperty;
        return base.GetCompositionProperty(name);
    }
}
[System.Flags]
enum InteractionTrackerChangedFields : ushort
{
    MinScale = 1,
    MinScaleAnimated = 2,
    MaxScale = 4,
    MaxScaleAnimated = 8,
    MinPosition = 16,
    MinPositionAnimated = 32,
    MaxPosition = 64,
    MaxPositionAnimated = 128,
    PositionInertiaDecayRate = 256,
    PositionInertiaDecayRateAnimated = 512,
    ScaleInertiaDecayRate = 1024,
    ScaleInertiaDecayRateAnimated = 2048,
    Scale = 4096,
    ScaleAnimated = 8192,
    Position = 16384,
    PositionAnimated = 32768
}
