on:
    workflow_dispatch:
    push:
        tags:
            - "*"

name: Deploy GitHub Pages

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    publish:
        name: Deploy GitHub Pages
        runs-on: windows-latest
        steps:
            - name: Setup environments
              id: vars
              run: |
                  git config --global core.symlinks true
                  git config --global core.autocrlf false
                  echo "dotnet_workload_version=$(dotnet workload --version)" >> $env:GITHUB_OUTPUT
                  echo "program_data=$env:ProgramData" >> $env:GITHUB_OUTPUT
            - uses: olegtarasov/get-tag@v2-release
              id: tag_name
            - name: Cache .NET workloads
              uses: actions/cache/restore@v5
              with:
                  key: dotnet-${{ runner.os }}-${{ runner.arch }}-workloads-${{ steps.vars.outputs.dotnet_workload_version }}
                  path: ${{ steps.vars.outputs.program_data }}\dotnet\workloads
            - name: Setup .NET workloads
              run: |
                  dotnet workload install wasm-tools
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v3
              with:
                  msbuild-architecture: x64
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  submodules: true
            - name: Cache NuGet packages
              uses: actions/cache/restore@v5
              if: ${{ github.event_name != 'workflow_dispatch' }}
              with:
                  key: dotnet-${{ runner.os }}-${{ runner.arch }}-nuget-${{ hashFiles('**/Directory.Packages.props') }}
                  path: ~/.nuget/packages
            - name: Build GitHub Pages
              if: ${{ github.event_name == 'workflow_dispatch' || !contains(steps.tag_name.outputs.tag, '-') }}
              run: |
                  $env:VERSION_SUFFIX = "${{ steps.tag_name.outputs.tag }}" -replace "^[^\-]+-?", ""
                  dotnet publish ./samples/SmoothScroll.Avalonia.Sample.Browser/SmoothScroll.Avalonia.Sample.Browser.csproj -f net10.0-browser /m:1
            - name: Deploy to GitHub Pages
              if: ${{ !contains(steps.tag_name.outputs.tag, '-') }}
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./samples/SmoothScroll.Avalonia.Sample.Browser/bin/Release/net10.0-browser/publish/wwwroot
                  publish_branch: gh-pages
